name: moshi_build
description: 'Build env.'
runs:
  using: "composite"
  steps:
  - uses: actions/setup-python@v5
    with:
      python-version: '3.10'
  - name: Install uv
    uses: astral-sh/setup-uv@v6
    with:
      version: "0.8.13"
  - name: Install dependencies
    shell: bash
    run: |
      uv venv env
      source env/bin/activate
      uv pip install torch==2.4.0 --index-url https://download.pytorch.org/whl/cpu
  - name: Setup env
    shell: bash
    run: |
      source env/bin/activate
      uv pip install -e './moshi[dev]'
      pre-commit install
